application: assassinwar-huanshi
version: 1
runtime: go
api_version: go1

handlers:

# The root URL (/) is handled by the Go application. No other URLs match this pattern.
- url: / 
  static_files: index.html 
  upload: index\.html 

- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /json
  static_dir: json
  
# All other URLs are handled by the Go application.
- url: /.*
  script: _go_app